var app = angular.module('app', [])
  .controller('AppController', ['$scope', function($scope) {
    var vm = this;

    vm.number = 1040;
    vm.getItems = function(num) {
      return new Array(num);
    }
    
    vm.colors = ['black', 'darkgrey', 'grey', 'white', 'saddlebrown', 'sienna', 'darkgoldenrod', 'peru', 'burlywood', 'tan', 'beige', 'maroon', 'brown', 'red', 'tomato', 'lightcoral', 'salmon', 'lightpink', 'thistle', 'chocolate', 'darkorange', 'sandybrown', 'orange', 'yellow', 'khaki', 'darkviolet', 'mediumorchid', 'plum', 'darkslateblue', 'blue', 'mediumpurple', 'steelblue', 'royalblue', 'cadetblue', 'skyblue', 'darkgreen', 'forestgreen', 'green', 'seagreen', 'mediumseagreen', 'limegreen'];
    vm.activeColor = vm.colors[0];

    vm.addHoverColor = function(color, index) {
      if (!vm.getItems[index] || (vm.getItems[index].indexOf('pearl') > 0 && vm.getItems[index].indexOf('hover') > 0)) {
        vm.getItems[index] = 'pearl-' + color + '-hover';
      }
    }

    vm.removeHoverColor = function(index) {
      if (vm.getItems[index].indexOf('hover') > 0) {
        vm.getItems[index] = '';
      }
    }

    vm.setColor = function(color, index) {
      if (vm.getItems[index] === 'pearl-' + color) {
        vm.getItems[index] = '';
      } else {
        vm.getItems[index] = 'pearl-' + color;
      }
    }
    
    vm.resetGrid = function() {
      angular.forEach(vm.getItems, function(value, key) {
        vm.getItems[key] = '';
      });
    }
    
    
    vm.getItems[254]="pearl-black",
    vm.getItems[255]="pearl-black",
    vm.getItems[256]="pearl-black",
    vm.getItems[257]="pearl-black",
    vm.getItems[258]="pearl-black",
    vm.getItems[260]="pearl-black",
    vm.getItems[261]="pearl-black",
    vm.getItems[292]="pearl-black",
    vm.getItems[293]="pearl-black",
    vm.getItems[294]="pearl-salmon",
    vm.getItems[295]="pearl-lightpink",
    vm.getItems[296]="pearl-lightpink",
    vm.getItems[297]="pearl-lightpink",
    vm.getItems[298]="pearl-salmon",
    vm.getItems[299]="pearl-black",
    vm.getItems[300]="pearl-salmon",
    vm.getItems[301]="pearl-lightpink",
    vm.getItems[302]="pearl-black",
    vm.getItems[331]="pearl-black",
    vm.getItems[332]="pearl-salmon",
    vm.getItems[333]="pearl-lightpink",
    vm.getItems[334]="pearl-lightpink",
    vm.getItems[335]="pearl-lightpink",
    vm.getItems[336]="pearl-lightpink",
    vm.getItems[337]="pearl-lightpink",
    vm.getItems[338]="pearl-lightpink",
    vm.getItems[339]="pearl-lightpink",
    vm.getItems[340]="pearl-black",
    vm.getItems[341]="pearl-lightpink",
    vm.getItems[342]="pearl-lightpink",
    vm.getItems[343]="pearl-black",
    vm.getItems[370]="pearl-black",
    vm.getItems[371]="pearl-salmon",
    vm.getItems[372]="pearl-lightpink",
    vm.getItems[373]="pearl-lightpink",
    vm.getItems[374]="pearl-lightpink",
    vm.getItems[375]="pearl-black",
    vm.getItems[376]="pearl-lightpink",
    vm.getItems[377]="pearl-black",
    vm.getItems[378]="pearl-lightpink",
    vm.getItems[379]="pearl-lightpink",
    vm.getItems[380]="pearl-lightpink",
    vm.getItems[381]="pearl-salmon",
    vm.getItems[382]="pearl-lightpink",
    vm.getItems[383]="pearl-black",
    vm.getItems[410]="pearl-black",
    vm.getItems[411]="pearl-lightpink",
    vm.getItems[412]="pearl-lightpink",
    vm.getItems[413]="pearl-lightpink",
    vm.getItems[414]="pearl-lightpink",
    vm.getItems[415]="pearl-black",
    vm.getItems[416]="pearl-lightpink",
    vm.getItems[417]="pearl-black",
    vm.getItems[418]="pearl-lightpink",
    vm.getItems[419]="pearl-lightpink",
    vm.getItems[420]="pearl-lightpink",
    vm.getItems[421]="pearl-salmon",
    vm.getItems[422]="pearl-salmon",
    vm.getItems[423]="pearl-black",
    vm.getItems[449]="pearl-black",
    vm.getItems[450]="pearl-lightpink",
    vm.getItems[451]="pearl-lightpink",
    vm.getItems[452]="pearl-lightpink",
    vm.getItems[453]="pearl-lightpink",
    vm.getItems[454]="pearl-lightpink",
    vm.getItems[455]="pearl-black",
    vm.getItems[456]="pearl-lightpink",
    vm.getItems[457]="pearl-black",
    vm.getItems[458]="pearl-lightpink",
    vm.getItems[459]="pearl-lightpink",
    vm.getItems[460]="pearl-lightpink",
    vm.getItems[461]="pearl-lightpink",
    vm.getItems[462]="pearl-salmon",
    vm.getItems[463]="pearl-black",
    vm.getItems[488]="pearl-black",
    vm.getItems[489]="pearl-salmon",
    vm.getItems[490]="pearl-lightpink",
    vm.getItems[491]="pearl-lightpink",
    vm.getItems[492]="pearl-lightpink",
    vm.getItems[493]="pearl-salmon",
    vm.getItems[494]="pearl-salmon",
    vm.getItems[495]="pearl-lightpink",
    vm.getItems[496]="pearl-lightpink",
    vm.getItems[497]="pearl-lightpink",
    vm.getItems[498]="pearl-salmon",
    vm.getItems[499]="pearl-salmon",
    vm.getItems[500]="pearl-lightpink",
    vm.getItems[501]="pearl-lightpink",
    vm.getItems[502]="pearl-lightpink",
    vm.getItems[503]="pearl-black",
    vm.getItems[528]="pearl-black",
    vm.getItems[529]="pearl-lightpink",
    vm.getItems[530]="pearl-lightpink",
    vm.getItems[531]="pearl-salmon",
    vm.getItems[532]="pearl-lightpink",
    vm.getItems[533]="pearl-lightpink",
    vm.getItems[534]="pearl-lightpink",
    vm.getItems[535]="pearl-lightpink",
    vm.getItems[536]="pearl-black",
    vm.getItems[537]="pearl-lightpink",
    vm.getItems[538]="pearl-lightpink",
    vm.getItems[539]="pearl-lightpink",
    vm.getItems[540]="pearl-lightpink",
    vm.getItems[541]="pearl-lightpink",
    vm.getItems[542]="pearl-salmon",
    vm.getItems[543]="pearl-black",
    vm.getItems[568]="pearl-black",
    vm.getItems[569]="pearl-lightpink",
    vm.getItems[570]="pearl-lightpink",
    vm.getItems[571]="pearl-salmon",
    vm.getItems[572]="pearl-lightpink",
    vm.getItems[573]="pearl-lightpink",
    vm.getItems[574]="pearl-lightpink",
    vm.getItems[575]="pearl-lightpink",
    vm.getItems[576]="pearl-black",
    vm.getItems[577]="pearl-lightpink",
    vm.getItems[578]="pearl-lightpink",
    vm.getItems[579]="pearl-lightpink",
    vm.getItems[580]="pearl-lightpink",
    vm.getItems[581]="pearl-lightpink",
    vm.getItems[582]="pearl-black",
    vm.getItems[609]="pearl-black",
    vm.getItems[610]="pearl-black",
    vm.getItems[611]="pearl-black",
    vm.getItems[612]="pearl-lightpink",
    vm.getItems[613]="pearl-lightpink",
    vm.getItems[614]="pearl-lightpink",
    vm.getItems[615]="pearl-lightpink",
    vm.getItems[616]="pearl-lightpink",
    vm.getItems[617]="pearl-lightpink",
    vm.getItems[618]="pearl-lightpink",
    vm.getItems[619]="pearl-lightpink",
    vm.getItems[620]="pearl-lightpink",
    vm.getItems[621]="pearl-salmon",
    vm.getItems[622]="pearl-black",
    vm.getItems[648]="pearl-black",
    vm.getItems[649]="pearl-salmon",
    vm.getItems[650]="pearl-salmon",
    vm.getItems[651]="pearl-salmon",
    vm.getItems[652]="pearl-black",
    vm.getItems[653]="pearl-lightpink",
    vm.getItems[654]="pearl-lightpink",
    vm.getItems[655]="pearl-lightpink",
    vm.getItems[656]="pearl-lightpink",
    vm.getItems[657]="pearl-lightpink",
    vm.getItems[658]="pearl-lightpink",
    vm.getItems[659]="pearl-lightpink",
    vm.getItems[660]="pearl-lightpink",
    vm.getItems[661]="pearl-salmon",
    vm.getItems[662]="pearl-black",
    vm.getItems[688]="pearl-black",
    vm.getItems[689]="pearl-salmon",
    vm.getItems[690]="pearl-salmon",
    vm.getItems[691]="pearl-salmon",
    vm.getItems[692]="pearl-salmon",
    vm.getItems[693]="pearl-black",
    vm.getItems[694]="pearl-lightpink",
    vm.getItems[695]="pearl-lightpink",
    vm.getItems[696]="pearl-lightpink",
    vm.getItems[697]="pearl-lightpink",
    vm.getItems[698]="pearl-lightpink",
    vm.getItems[699]="pearl-lightpink",
    vm.getItems[700]="pearl-salmon",
    vm.getItems[701]="pearl-black",
    vm.getItems[728]="pearl-black",
    vm.getItems[729]="pearl-salmon",
    vm.getItems[730]="pearl-salmon",
    vm.getItems[731]="pearl-salmon",
    vm.getItems[732]="pearl-salmon",
    vm.getItems[733]="pearl-black",
    vm.getItems[734]="pearl-lightpink",
    vm.getItems[735]="pearl-lightpink",
    vm.getItems[736]="pearl-lightpink",
    vm.getItems[737]="pearl-lightpink",
    vm.getItems[738]="pearl-lightpink",
    vm.getItems[739]="pearl-salmon",
    vm.getItems[740]="pearl-black",
    vm.getItems[741]="pearl-black",
    vm.getItems[769]="pearl-black",
    vm.getItems[770]="pearl-salmon",
    vm.getItems[771]="pearl-salmon",
    vm.getItems[772]="pearl-salmon",
    vm.getItems[773]="pearl-salmon",
    vm.getItems[774]="pearl-black",
    vm.getItems[775]="pearl-salmon",
    vm.getItems[776]="pearl-salmon",
    vm.getItems[777]="pearl-salmon",
    vm.getItems[778]="pearl-black",
    vm.getItems[779]="pearl-black",
    vm.getItems[780]="pearl-salmon",
    vm.getItems[781]="pearl-salmon",
    vm.getItems[782]="pearl-black",
    vm.getItems[810]="pearl-black",
    vm.getItems[811]="pearl-salmon",
    vm.getItems[812]="pearl-salmon",
    vm.getItems[813]="pearl-black",
    vm.getItems[814]="pearl-black",
    vm.getItems[815]="pearl-black",
    vm.getItems[816]="pearl-black",
    vm.getItems[817]="pearl-black",
    vm.getItems[818]="pearl-salmon",
    vm.getItems[819]="pearl-salmon",
    vm.getItems[820]="pearl-salmon",
    vm.getItems[821]="pearl-salmon",
    vm.getItems[822]="pearl-salmon",
    vm.getItems[823]="pearl-black",
    vm.getItems[851]="pearl-black",
    vm.getItems[852]="pearl-black",
    vm.getItems[853]="pearl-black",
    vm.getItems[857]="pearl-black",
    vm.getItems[858]="pearl-black",
    vm.getItems[859]="pearl-black",
    vm.getItems[860]="pearl-black",
    vm.getItems[861]="pearl-black",
    vm.getItems[862]="pearl-black";
  }]);